title: CTF Writeups
description: Writeups for CTF and blogs on security topic.
show_downloads: false
url: https://devang-solanki.github.io/
#theme: jekyll-theme-cayman
remote_theme: pages-themes/slate@v0.2.0

github:
  is_project_page: false


plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    category: '/category/:name/'
