title: CTF Writeups
description: Writeups for CTF.
show_downloads: false
url: https://devang-solanki.github.io/writeups/tryhackme/haskhell
theme: jekyll-theme-hacker

github:
  is_project_page: false
